import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Campus Cuisine App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navigation Bar */}
        <nav className="flex justify-between items-center p-8">
          <Link href="/" className="flex items-center">
            <Image
              src="https://picsum.photos/100/80" // Replace with actual logo
              alt="Campus Cuisine Logo"
              width={100}
              height={80}
              className="mr-4 rounded-md"
            />
            <h1 className="text-2xl font-bold">Campus Cuisine</h1>
          </Link>
          <ul className="flex space-x-6">
            <li><Link href="/" className="hover:text-primary">Home</Link></li>
            <li><Link href="/pricing" className="hover:text-primary">Pricing</Link></li>
            <li><Link href="/contact" className="hover:text-primary">Contact</Link></li>
            <li><Link href="/meal-plan" className="hover:text-primary">Meal Plan</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}

